package org.example;

public enum eListGames {
    Minecraft,
    Grand_Theft_Auto_V,
    Tetris,
    Wii_Sports,
    PUBG_Battlegrounds,
    Mario_Kart_8_Deluxe,
    The_Elder_Scrolls_V_Skyrim,
    Super_Mario_Bros,
    Red_Dead_Redemption_2,
    The_Witcher_3,
    Hearts_of_Stone,
    Blood_and_Wine,
    Pokémon,
    Wii_Fit,
    Tetris_1989,
    Animal_Crossing_New_Horizons,
    Pac_Man,
    Mario_Kart_Wii,
    Wii_Sports_Resort,
    New_Super_Mario_Bros,
    New_Super_Mario_Bros_Wii,
    Call_of_Duty_Modern_Warfare,
    Diablo_III_Reaper_of_Souls,
    Human_Fall_Flat,
    Duck_Hunt,
    The_Legend_of_Zelda,
    Breath_of_the_Wild,
    }
